import { Button, VerticalBox } from "std-widgets.slint";

component MainWindow inherits Window {
    title: "DiagXpert";
    in-out property <bool> is_start: false;
    width: 300px;
    callback reset(int);
    HorizontalLayout {
        VerticalBox {
            Button {
                text: "ECU Reset";
                clicked => {
                    reset(1);
                }
            }
            Button {
                text: "Security Access";
                clicked => {
                    reset(2);
                }
            }
            Button {
                text: "Communication Control";
                clicked => {
                    reset(3);
                }
            }
        }
    }
}
