import { Button, VerticalBox } from "std-widgets.slint";

component MainWindow inherits Window {
    title: "DiagXpert";
    in-out property <bool> is_start: false;
    callback reset(int);
    HorizontalLayout {
        VerticalBox {
            Button {
                text: is_start?"stop":"start";
                clicked => {
                    reset(is_start?4:3);
                    is_start = !is_start;
                }
            }
            Button {
                text: "reset 118";
                clicked => {
                    reset(64);
                }
            }
            Button {
                text: "reset 148";
                clicked => {
                    reset(65);
                }
            }
            Button {
                text: "reset imx";
                clicked => {
                    reset(66);
                }
            }
            Button {
                text: "reset esp-wifi";
                clicked => {
                    reset(67);
                }
            }
            Button {
                text: "reset esp-ble";
                clicked => {
                    reset(68);
                }
            }
            Button {
                text: "reset lte";
                clicked => {
                    reset(69);
                }
            }
            Button {
                text: "reset lizard";
                clicked => {
                    reset(70);
                }
            }
            Button {
                text: "reset cendric";
                clicked => {
                    reset(71);
                }
            }
        }
    }
}
